var AdventureConstants = {
  ADVENTURES_RECEIVED: "ADVENTURES_RECEIVED",
  ADVENTURE_RECEIVED: 'ADVENTURE_RECEIVED',
  UNBOUNDED_RECEIEVD: "UNBOUNDED_RECEIEVD"
};

module.exports = AdventureConstants;
