# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c22879edfe54648f90e44844c8445f8b87852a5e06d99587df2e6dcde3530de3e8d01f60079927b8f6630111f0fdec26f468fd9dc438a0bede0ef552c56e82

test:
  secret_key_base: 99ae1a1e3b3ffce390963fe02749757b89071e82bf00f39c2acb31c9cd5b28fe95842793206fe90b1f5a0500d5b0e3def51fc4bcf18eefb7fbcc26fec79d3f86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
